In [2]:
import pandas as pd
# import matplotlib.pyplot as plt

In this project, we're going to analyze and operate on data from a CSV file.

Let's begin by downloading the CSV file.

In [3]:
# from urllib.request import urlretrieve

# urlretrieve('https://gist.githubusercontent.com/aakashns/28b2e504b3350afd9bdb157893f9725c/raw/994b65665757f4f8887db1c85986a897abb23d84/countries.csv', 
#             'countries.csv')

Let's load the data from the CSV file into a Pandas data frame.

In [4]:

countries_df = pd.read_csv('countries.csv')
# pd.set_option('display.max_rows', 210)

In [5]:
# view dataset
countries_df.head()

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987
1,Albania,Europe,2877800.0,78.57,2.89,11803.431
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839
3,Andorra,Europe,77265.0,83.73,NaN,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495

In [6]:
# rename column location to countires
countries_df = countries_df.rename(columns={'location':'countries'})

**Q1: How many countries does the dataframe contain?**

In [7]:
# Decided to use the .count() method rather than .shape for proper presenation
num_countries = countries_df.shape[0]
print('There are {} countries in the dataset'.format(num_countries))

There are 210 countries in the dataset

**Q2: Retrieve a list of continents from the dataframe?**

In [65]:
continents = list(countries_df.continent.unique())
print(continents)

['Asia', 'Europe', 'Africa', 'North America', 'South America', 'Oceania']

**Q3: What is the total population of all the countries listed in this dataset?**

In [9]:
total_population = countries_df['population'].sum()
print('The total population is {}.'.format(int(total_population)))

The total population is 7757980095.

**Q: What is the overall life expectancy across in the world?**

In [10]:
# take a weighted average of life expectancy using populations as weights

weighted_life_expectancy = (countries_df['life_expectancy'] * countries_df['population']).sum() / countries_df['population'].sum()

In [11]:
print(f'Therefore, the overall life expectancy across the world, using populations as weights, is approximately {weighted_life_expectancy:.0f} years.')

Therefore, the overall life expectancy across the world, using populations as weights, is approximately 73 years.

**Q4: Create a dataframe containing 10 countries with the highest population.**

In [12]:
most_populous_df = countries_df.sort_values(by='population', ascending=False)

In [13]:
most_populous_df.reset_index(drop=True, inplace=True)
most_populous_df.index +=1

In [14]:
most_populous_top10 =most_populous_df.head(10)

In [15]:
# View dataset most_populous_df
most_populous_top10

,countries,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
1,China,Asia,1.439324e+09,76.91,4.34,15308.712
2,India,Asia,1.380004e+09,69.66,0.53,6426.674
3,United States,North America,3.310026e+08,78.86,2.77,54225.446
4,Indonesia,Asia,2.735236e+08,71.72,1.04,11188.744
5,Pakistan,Asia,2.208923e+08,67.27,0.60,5034.708
6,Brazil,South America,2.125594e+08,75.88,2.20,14103.452
7,Nigeria,Africa,2.061396e+08,54.69,NaN,5338.454
8,Bangladesh,Asia,1.646894e+08,72.59,0.80,3523.984
9,Russia,Europe,1.459345e+08,72.58,8.05,24765.954
10,Mexico,North America,1.289328e+08,75.05,1.38,17336.469

**Q5: Add a new column in `countries_df` to record the overall GDP per country (product of population & per capita GDP).**

In [16]:
countries_df['gdp'] = countries_df['population'] * countries_df['gdp_per_capita']

In [17]:
countries_df.head()

,countries,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987,7.022622e+10
1,Albania,Europe,2877800.0,78.57,2.89,11803.431,3.396791e+10
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839,6.101364e+11
3,Andorra,Europe,77265.0,83.73,NaN,NaN,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495,1.912651e+11

**Q: Create a dataframe containing 10 countries with the lowest GDP per capita, among the counties with population greater than 100 million.**

In [18]:
# countries_df[countries_df['population'] > 100000000].sort_values(by='gdp_per_capita')
lowest_gpa = countries_df.query('population > 100000000').sort_values(by='gdp_per_capita')

In [19]:
#reset_index_row_number
lowest_gpa.reset_index(drop=True, inplace=True)
lowest_gpa.index += 1

In [20]:
lowest_gpa_top10 = lowest_gpa.head(10)

In [21]:
# print dataframe
lowest_gpa_top10

,countries,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp
1,Ethiopia,Africa,1.149636e+08,66.60,0.30,1729.927,1.988786e+11
2,Bangladesh,Asia,1.646894e+08,72.59,0.80,3523.984,5.803628e+11
3,Pakistan,Asia,2.208923e+08,67.27,0.60,5034.708,1.112128e+12
4,Nigeria,Africa,2.061396e+08,54.69,NaN,5338.454,1.100467e+12
5,India,Asia,1.380004e+09,69.66,0.53,6426.674,8.868838e+12
6,Philippines,Asia,1.095811e+08,71.23,1.00,7599.188,8.327273e+11
7,Egypt,Africa,1.023344e+08,71.99,1.60,10550.206,1.079649e+12
8,Indonesia,Asia,2.735236e+08,71.72,1.04,11188.744,3.060386e+12
9,Brazil,South America,2.125594e+08,75.88,2.20,14103.452,2.997821e+12
10,China,Asia,1.439324e+09,76.91,4.34,15308.712,2.203419e+13

**Q6: Create a data frame that counts the number countries in each continent?**

In [22]:
country_counts_df = countries_df.groupby('continent')['countries'].count()

In [23]:
# sort from highest to lowest
country_counts_df.sort_values(ascending=False)

continent
Africa           55
Europe           51
Asia             47
North America    36
South America    13
Oceania           8
Name: countries, dtype: int64

**Q7: Create a data frame showing the total population of each continent.**

In [24]:
continent_populations_df = countries_df.groupby('continent')['population'].sum()

In [25]:
# sort from highest to lowest
continent_populations_df.sort_values(ascending=False)

continent
Asia             4.607388e+09
Africa           1.339424e+09
Europe           7.485062e+08
North America    5.912425e+08
South America    4.304611e+08
Oceania          4.095832e+07
Name: population, dtype: float64

Let's download another CSV file containing overall Covid-19 stats for various countires, and read the data into another Pandas data frame.

In [26]:
# urlretrieve('https://gist.githubusercontent.com/aakashns/b2a968a6cfd9fbbb0ff3d6bd0f26262b/raw/b115ed1dfa17f10fc88bf966236cd4d9032f1df8/covid-countries-data.csv', 
#             'covid-countries-data.csv')

In [27]:
covid_data_df = pd.read_csv('covid-countries-data.csv')

In [28]:
print(covid_data_df.columns)

Index(['location', 'total_cases', 'total_deaths', 'total_tests'], dtype='object')

In [29]:
# rename column location to countries
covid_data_df = covid_data_df.rename(columns={'location':'countries'})

In [30]:
covid_data_df.head()

     countries  total_cases  total_deaths  total_tests
0  Afghanistan      38243.0        1409.0          NaN
1      Albania       9728.0         296.0          NaN
2      Algeria      45158.0        1525.0          NaN
3      Andorra       1199.0          53.0          NaN
4       Angola       2729.0         109.0          NaN

**Q8: Count the number of countries for which the `total_tests` data is missing.**

In [31]:
total_tests_missing = covid_data_df['total_tests'].isna().sum()

In [32]:
print(f"{total_tests_missing} Countries total tests is missing ")

122 Countries total tests is missing



**Q9: Merge `countries_df` with `covid_data_df` on the `countries` column.**

In [33]:
# Using inner join by default to combine both tables with matching data
combined_df = pd.merge(countries_df,covid_data_df, on='countries')

**Q10: Add columns `tests_per_million`, `cases_per_million` and `deaths_per_million` into `combined_df`.**

In [34]:
combined_df['tests_per_million'] = combined_df['total_tests'] * 1e6 / combined_df['population']

In [35]:
combined_df['cases_per_million'] = combined_df['total_cases'] * 1e6 / combined_df['population']

In [36]:
combined_df['deaths_per_million'] = combined_df['total_deaths'] * 1e6 / combined_df['population']

In [37]:
# print dataframe
combined_df

,countries,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987,7.022622e+10,38243.0,1409.0,NaN,NaN,982.394806,36.194710
1,Albania,Europe,2877800.0,78.57,2.89,11803.431,3.396791e+10,9728.0,296.0,NaN,NaN,3380.359997,102.856349
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839,6.101364e+11,45158.0,1525.0,NaN,NaN,1029.804468,34.776824
3,Andorra,Europe,77265.0,83.73,NaN,NaN,NaN,1199.0,53.0,NaN,NaN,15518.022390,685.950948
4,Angola,Africa,32866268.0,61.15,NaN,5819.495,1.912651e+11,2729.0,109.0,NaN,NaN,83.033462,3.316470
...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884,6.007624e+11,1046.0,35.0,261004.0,2681.403324,10.745996,0.359570
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN,NaN,766.0,1.0,NaN,NaN,1282.373228,1.674116
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147,4.411699e+10,1976.0,571.0,NaN,NaN,66.250993,19.144391
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251,6.782303e+10,12415.0,292.0,NaN,NaN,675.317108,15.883415
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775,2.823622e+10,6638.0,206.0,97272.0,6544.605918,446.614587,13.859989

**Q11: Create a dataframe with 10 countires that have highest number of tests per million people.**

In [38]:
highest_tests_df = (combined_df[['countries', 'continent','tests_per_million']]
                    .sort_values(by="tests_per_million", ascending=False)
                    .dropna())

#reset the original index value to suit the result
highest_tests_df.reset_index(drop=True, inplace=True)
highest_tests_df.index += 1

In [39]:
highest_tests_top10 = highest_tests_df.head(10)

In [40]:
highest_tests_top10

               countries      continent  tests_per_million
1   United Arab Emirates           Asia      725696.635121
2                Bahrain           Asia      657527.137965
3             Luxembourg         Europe      616349.508607
4                  Malta         Europe      427004.183096
5                Denmark         Europe      422621.755488
6                 Israel           Asia      271962.665303
7                Iceland         Europe      260304.761905
8                 Russia         Europe      254750.159763
9          United States  North America      253467.507769
10             Australia        Oceania      245326.517406

**Q12: Create a dataframe with 10 countires that have highest number of positive cases per million people.**

In [41]:
highest_cases_df = (combined_df[['countries', 'continent','cases_per_million']]
                    .sort_values(by="cases_per_million", ascending=False)
                    .dropna())

#reset the original index value to suit the result
highest_cases_df.reset_index(drop=True, inplace=True)
highest_cases_df.index += 1

In [42]:
highest_cases_top10 = highest_cases_df.head(10)

In [43]:
highest_cases_top10

        countries      continent  cases_per_million
1           Qatar           Asia       41375.743650
2         Bahrain           Asia       30818.361490
3          Panama  North America       21805.112117
4           Chile  South America       21695.671982
5      San Marino         Europe       21657.139490
6           Aruba  North America       20708.839893
7          Kuwait           Asia       20249.789079
8            Peru  South America       20121.318048
9          Brazil  South America       18808.224105
10  United States  North America       18472.377957

In [44]:
highest_cases_top10['cases_per_million'] = highest_cases_top10['cases_per_million'] * 1e6

C:\Users\GeeOc\AppData\Local\Temp\ipykernel_17636\656435081.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highest_cases_top10['cases_per_million'] = highest_cases_top10['cases_per_million'] * 1e6

In [45]:
highest_cases_top10

        countries      continent  cases_per_million
1           Qatar           Asia       4.137574e+10
2         Bahrain           Asia       3.081836e+10
3          Panama  North America       2.180511e+10
4           Chile  South America       2.169567e+10
5      San Marino         Europe       2.165714e+10
6           Aruba  North America       2.070884e+10
7          Kuwait           Asia       2.024979e+10
8            Peru  South America       2.012132e+10
9          Brazil  South America       1.880822e+10
10  United States  North America       1.847238e+10

In [46]:
highest_cases_top10.to_csv("Highest_cases_top10.csv", index=False)

**Q13: Create a dataframe with 10 countires that have highest number of deaths cases per million people?**

In [47]:
highest_deaths_df = (combined_df[['countries', 'continent','deaths_per_million']]
                     .sort_values(by="deaths_per_million", ascending=False)
                     .dropna())

#reset the original index value to suit the result
highest_deaths_df.reset_index(drop=True, inplace=True)
highest_deaths_df.index +=1

In [48]:
highest_deaths_top10 = highest_deaths_df.head(10)

In [49]:
highest_deaths_top10

         countries      continent  deaths_per_million
1       San Marino         Europe         1237.550828
2             Peru  South America          887.393445
3          Belgium         Europe          854.040375
4          Andorra         Europe          685.950948
5            Spain         Europe          624.406705
6   United Kingdom         Europe          611.525168
7            Chile  South America          593.423100
8            Italy         Europe          587.097697
9           Brazil  South America          582.331314
10          Sweden         Europe          576.279276

**Q: Count number of countries that feature in both the lists of "highest number of tests per million" and "highest number of cases per million".**

In [50]:
# merge highest_cases_df and highest_tests_df
check = pd.merge(highest_cases_df,highest_tests_df, on='countries')

#count the dataset using len function

number = len(check)

In [51]:
print(f'There are {number} countries that featured in both the lists of "highest number of tests per million" and "highest number of cases per million')

There are 89 countries that featured in both the lists of "highest number of tests per million" and "highest number of cases per million

**Q: Count number of countries that feature in both the lists "20 countries with lowest GDP per capita" and "20 countries with the lowest number of hospital beds per thousand population". Only consider countries with a population higher than 10 million while creating the list.**

In [52]:
lowest_gpa_per_capita = combined_df[['countries','continent','population','gdp_per_capita']].sort_values(by='gdp_per_capita')

lowest_gpa_per_capita.reset_index(drop=True, inplace=True)
lowest_gpa_per_capita.index += 1

In [53]:
lowest_gpa_per_capita_top20 = lowest_gpa_per_capita.head(20)

In [54]:
lowest_gpa_per_capita_top20

                       countries      continent   population  gdp_per_capita
1       Central African Republic         Africa    4829764.0         661.240
2                        Burundi         Africa   11890781.0         702.225
3                        Liberia         Africa    5057677.0         752.788
4   Democratic Republic of Congo         Africa   89561404.0         808.133
5                          Niger         Africa   24206636.0         926.000
6                         Malawi         Africa   19129955.0        1095.042
7                     Mozambique         Africa   31255435.0        1136.103
8                   Sierra Leone         Africa    7976985.0        1390.300
9                        Comoros         Africa     869595.0        1413.890
10                    Madagascar         Africa   27691019.0        1416.440
11                          Togo         Africa    8278737.0        1429.813
12                         Yemen           Asia   29825968.0        1479.147
13                       Eritrea         Africa    3546427.0        1510.459
14                 Guinea-Bissau         Africa    1967998.0        1548.675
15                        Gambia         Africa    2416664.0        1561.767
16                   South Sudan         Africa   11193729.0        1569.888
17                         Haiti  North America   11402533.0        1653.173
18                        Uganda         Africa   45741000.0        1697.707
19                  Burkina Faso         Africa   20903278.0        1703.102
20                      Ethiopia         Africa  114963583.0        1729.927

In [55]:
lowest_hospital_beds_per_thousand = combined_df[['countries','continent','population','hospital_beds_per_thousand']].sort_values(by='hospital_beds_per_thousand')

lowest_hospital_beds_per_thousand.reset_index(drop=True, inplace=True)
lowest_hospital_beds_per_thousand.index += 1

In [56]:
lowest_hospital_beds_per_thousand_top20 = lowest_hospital_beds_per_thousand.head(20)

In [57]:
lowest_hospital_beds_per_thousand_top20

       countries      continent    population  hospital_beds_per_thousand
1           Mali         Africa  2.025083e+07                        0.10
2     Madagascar         Africa  2.769102e+07                        0.20
3         Guinea         Africa  1.313279e+07                        0.30
4       Ethiopia         Africa  1.149636e+08                        0.30
5          Nepal           Asia  2.913681e+07                        0.30
6          Niger         Africa  2.420664e+07                        0.30
7   Burkina Faso         Africa  2.090328e+07                        0.40
8    Afghanistan           Asia  3.892834e+07                        0.50
9         Uganda         Africa  4.574100e+07                        0.50
10         Benin         Africa  1.212320e+07                        0.50
11         India           Asia  1.380004e+09                        0.53
12      Pakistan           Asia  2.208923e+08                        0.60
13     Guatemala  North America  1.791557e+07                        0.60
14          Togo         Africa  8.278737e+06                        0.70
15         Yemen           Asia  2.982597e+07                        0.70
16         Haiti  North America  1.140253e+07                        0.70
17      Honduras  North America  9.904608e+06                        0.70
18       Eritrea         Africa  3.546427e+06                        0.70
19      Tanzania         Africa  5.973421e+07                        0.70
20    Mozambique         Africa  3.125544e+07                        0.70

In [58]:
subset = pd.merge(lowest_gpa_per_capita_top20, lowest_hospital_beds_per_thousand_top20, on='countries')

In [59]:
subset

,countries,continent_x,population_x,gdp_per_capita,continent_y,population_y,hospital_beds_per_thousand
0,Niger,Africa,24206636.0,926.000,Africa,24206636.0,0.3
1,Mozambique,Africa,31255435.0,1136.103,Africa,31255435.0,0.7
2,Madagascar,Africa,27691019.0,1416.440,Africa,27691019.0,0.2
3,Togo,Africa,8278737.0,1429.813,Africa,8278737.0,0.7
4,Yemen,Asia,29825968.0,1479.147,Asia,29825968.0,0.7
5,Eritrea,Africa,3546427.0,1510.459,Africa,3546427.0,0.7
6,Haiti,North America,11402533.0,1653.173,North America,11402533.0,0.7
7,Uganda,Africa,45741000.0,1697.707,Africa,45741000.0,0.5
8,Burkina Faso,Africa,20903278.0,1703.102,Africa,20903278.0,0.4
9,Ethiopia,Africa,114963583.0,1729.927,Africa,114963583.0,0.3

In [60]:
subset = subset[['countries','continent_x','population_x','gdp_per_capita','hospital_beds_per_thousand']].query("population_x > 10000000")

subset = subset.reset_index(drop=True)

subset.index += 1

In [61]:
# rename columns
subset = subset.rename(columns={'continent_x': 'continent','population_x': 'population'})

In [62]:
subset

,countries,continent,population,gdp_per_capita,hospital_beds_per_thousand
1,Niger,Africa,24206636.0,926.000,0.3
2,Mozambique,Africa,31255435.0,1136.103,0.7
3,Madagascar,Africa,27691019.0,1416.440,0.2
4,Yemen,Asia,29825968.0,1479.147,0.7
5,Haiti,North America,11402533.0,1653.173,0.7
6,Uganda,Africa,45741000.0,1697.707,0.5
7,Burkina Faso,Africa,20903278.0,1703.102,0.4
8,Ethiopia,Africa,114963583.0,1729.927,0.3

In [63]:
num_of_countries_feature = subset.shape[0]

In [64]:
print(f'There are {num_of_countries_feature} Countries that feature in both the lists "20 countries with lowest GDP per capita" and "20 countries with the lowest number of hospital beds per thousand population". Considering Countries with a population higher than 10 million ')

There are 8 Countries that feature in both the lists "20 countries with lowest GDP per capita" and "20 countries with the lowest number of hospital beds per thousand population". Considering Countries with a population higher than 10 million